brew "git"
brew "neovim"
brew "stow"
brew "fzf"
brew "fzf-tab"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zoxide"
brew "fd"
brew "ripgrep"
brew "tree-sitter-cli"
# Node supports npm-based Neovim tools and the repository lint commands.
brew "node"
brew "lazygit"
brew "graphviz"
brew "shellcheck"
brew "starship"
